### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by Lethephyr** [manman1995/pansharpening#1]
你好，请问能分享一下数据集的链接吗？

**Comment by manman1995** [comment]
方便的话，你可以加一下微信，我们share给你

在2023-04-22 19:00:09，Jiazhan ***@***.***写道：

你好，请问能分享一下数据集的链接吗？

**Comment by manman1995** [comment]
https://pan.baidu.com/s/12XqgR3l4m-WBxGOw4W807A?pwd=i1dk code: i1dk

**Comment by zahrabsh74** [comment]
dear @manman1995 , thanks for your nice work!
I wanted to use your dataset in pansharpening models but it is not possible for me to download your dataset from this link! I am not sure is it possible for non-Chinese people to use this dataset? because this dataset is just possible to be downloaded by some Chinese app and registered by Chinese phone number. if there is any other simple way to use this dataset I would be thankful if you could help me.
